version: "3"

services:
  service_mongo:
    image: mongo
    container_name: service_mongo
    restart: on-failure
    volumes: 
      - db-data:/data/db
    networks: 
      - service-private
    environment: 
      - NODE_ENV=dev
  service_server:
    build: .
    restart: on-failure
    container_name: service_server
    volumes: 
      - ./src:/app/src
      - ./app.js:/app/app.js
    networks: 
      - service-private
    depends_on: 
      - service_mongo
  service_nginx:
    build: ./nginx
    container_name: service_nginx
    restart: on-failure
    depends_on: 
      - service_server
    networks: 
      - service-private
      - service-public
    ports: 
      - 9000:9000

volumes: 
  db-data:

networks: 
  service-private:
  service-public: