module.exports = {
    RESERVATION_PANDING: 'PANDING',
    RESERVATION_ACCEPTED: 'ACCEPTED',
    RESERVATION_DECLINED: 'DECLINED',
    RESERVATION_IN_PROGRESS: 'IN_PROGRESS',
    RESERVATION_DONE: 'DONE',

    PROBLEM_EASY: 'EASY',
    PROBLEM_MEDIUM: 'MEDIUM',
    PROBLEM_HARD: 'HARD'
}