module.exports = {
    RESERVATION_PANDING: 'PENDING',
    RESERVATION_ACCEPTED: 'ACCEPTED',
    RESERVATION_DECLINED: 'DECLINED',
    RESERVATION_IN_PROGRESS: 'IN_PROGRESS',
    RESERVATION_DONE: 'DONE',

    CAR_PROBLEMS: ['EASY', 'MEDIUM', 'HARD'],
    VACATION_REQUEST_STATUS: {
        ACCEPTED: 'ACCEPTED',
        DECLINED: 'DECLINED',
        PENDING: 'PENDING'
    },
    USER_STATUS: {
        AVAILABLE: 'AVAILABLE',
        ON_VACATION: 'ONVACATION'
    },

    EMPLOYEE: 'EMPLOYEE',

    DEFAULT_IMAGE_WIDTH: 1024,
    NOTIFICATION_TIME: 60 * 60 * 24 * 10000,
    NOTIFICATION_FORMAT: 'days',
    NOTIFICATION_FORMAT_TYPE: {
        MINUTES: 'minutes',
        DAYS: 'days',
        HOURS: 'hours'
    }
}