module.exports = {
    RESERVATION_PANDING: 'PANDING',
    RESERVATION_ACCEPTED: 'ACCEPTED',
    RESERVATION_DECLINED: 'DECLINED',
    RESERVATION_IN_PROGRESS: 'IN_PROGRESS',
    RESERVATION_DONE: 'DONE',

    CAR_PROBLEMS: ['EASY', 'MEDIUM', 'HARD'],

    DEFAULT_IMAGE_WIDTH: 1024,
    NOTIFICATION_TIME: 24 * 60 * 60 * 1000
}